### ISSUE TITLE
[4pt]  - Display number of likes for each item on the Homepage - Student A

### ISSUE THREAD

**Issue by lucas-crodrigues** [lucas-crodrigues/js-capstone#12]
When the page loads, the webapp the [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) to show the item likes and combines them with the data from the base API.

Remember that your page should make only 2 requests:
- one to the base API
- and **one** to the Involvement API.

This task **does not** include displaying the likes button (heart icon on the wireframe) for each item.

**Comment by Hannziegel** [comment]
Hi @lucas-crodrigues , 

![lord-of-the-rings-gandalf](https://user-images.githubusercontent.com/47539402/181387244-a61ec643-df31-4e35-9721-4c36f216c9d3.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 👍 👍 👍  
Congratulations! 🎉 

## Highlights
- Descriptive Pull request :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 
- Clean code :heavy_check_mark:  
- Great UI :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
