### ISSUE TITLE
Peer to Peer Code Review 28/07

### ISSUE THREAD

**Issue by Hannziegel** [lucas-crodrigues/js-capstone#29]
Hello, @lucas-crodrigues 😺 
Your code is looking great 🔥 🔥 🔥 

But still have room for some improvement, please check the comments below: 

# Item Counter Functionality :
- You can create a const counter and increase their value whenever you populate the HTML instead of getting the length of the items array.

**Comment by lucas-crodrigues** [comment]
Thank you for the feedback, cheers! 👍
